backend:
  name: github
  branch: main
  repo: nguyenquyynh/cms.doc
  local_backend: true

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: Docs (Viet Nam) 
  label: "Docs (Viet Nam)"
  folder: docs
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  nested: 
    depth: 3
    summary: '{{title}}'
  summary: '{{filename}}'
  fields:
    - { name: sidebar_position, label: Position, widget: number }
    - { name: label, label: label, widget: string }
    - { name: title, label: File Name, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string, required: false }
    - label: "Tags"
      name: "tags"
      required: false
      widget: "list"
- name: Docs (English)
  label: "Docs (English)"
  folder: i18n/en/docusaurus-plugin-content-docs/current
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  nested: 
    depth: 3
    summary: '{{filename}}'
  fields:
    - { name: sidebar_position, label: Position, widget: number }
    - { name: label, label: label, widget: string }
    - { name: title, label: File Name, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string, required: false }
    - label: "Tags"
      name: "tags"
      required: false
      widget: "list"